### ISSUE TITLE
mpc-web demo does not work

### ISSUE THREAD

**Issue by hurbeana** [multiparty/jiff#184]
Hello,
I've been trying to get the mpc-web demo to work, but there always seem to be something that breaks it. I fixed some things (such as the socket event string at the server being "init" instead of the expected "initialization") but now everything gets stuck after everybody connected and the analyst starting by receiving the enter.

After some debugging it seems the analyst never receives the socket message from the server how many clients are connected, thus the analyst can't continue.

Sadly I don't have enough experience to fix this myself, I tried, but failed at this part because I can't find the reason why the analyst doesn't receive the message.

Kind regards,
hurbeana

**Comment by KinanBab** [comment]
I can replicate this behavior. This is partly related to some recent pushes that changed some of the internal API in JIFF.

Will fix this soon.

Thanks for bringing this to our attention

**Comment by KinanBab** [comment]
This is finally fixed. Demo was also cleaned-up with some more explanations and useful links.
