### ISSUE TITLE
mpc-as-a-service does not work

### ISSUE THREAD

**Issue by ReoYoneyama** [multiparty/jiff#188]
Hello. I want to use JIFF, separating MPC nodes into input only node and compute only node. So I have been trying to use and understand the mpc-as-a-service in demos. However, it does not work because of some reasons and I cannot resolve them. Let me tell the situation specifically. 

First, I activate the server with a command of  "node demos/mpc-as-a-service/server.js". Then I activate compute parties with the command of "node demos/mpc-as-a-service/compute-party.js". Of course, I activate them including the server in distinct terminals. Next, I activate input parties in browser via http://localhost:8080/demos/mpc-as-a-service/client.html and connect input parties one by one. But when I try to connect the last input party, all compute parties disconnect suddenly. The error message is "Error: No preprocessed value(s) that correspond to the op_id "open:1,2:1,2,3,4:0:refresh" ". 

Would you tell me the solution?

**Comment by KinanBab** [comment]
Hello, This is my bad. I left this demo in an inconsistent state after the last big merge. I will fix it and ping you back in a day.

**Comment by ReoYoneyama** [comment]
Thank you!

**Comment by KinanBab** [comment]
Hello,

Thanks for the issue. I just fixed the demo and pushed it. You should have no issues running it.

The issue you reported is the result of preprocessing, an advanced feature we rolled out that allows a specified subset of parties to perform MPC preprocessing prior to the actual computation to speed it up.

This can be turned off by setting the crypto_provider initialization parameter to true, which will fallback to using the server for the preprocessing material on demand. This is how this demo is currently setup, there are comments inside compute-party.js that instruct you how to switch preprocessing on (~3 lines)

I am unsure if this is interesting to you, but preprocessing is relevant in certain scenarios depending on the trust relations and security you are going for. In case you are interested in learning more about it, please check the newly updated preprocessing tutorial (run `npm run tutorial` and follow the preprocessing link displayed)

Please let me know if you encounter other issues with this demo or others.

**Comment by ReoYoneyama** [comment]
Thank you! I confirmed that the demo runs with no errors!
I understood the merit of preprocessing thanks to your explanation and  the tutorial.
