### ISSUE TITLE
share and compute array as mpc-as-a-service

### ISSUE THREAD

**Issue by ReoYoneyama** [multiparty/jiff#189]
Hello. 
I want to have compute-parties execute computation using arrays from input-parties as mpc-as-a-service.
I'm trying to do that referring some demos such as mpc-as-a-service, array-bubble-sort and etc.
However, I encounter some troubles when I try to open the computation result in compute-party.js.
It doesn't emit any error message, but "final_promise" in open.js never fulfilled (forever "pending" state). I think this situation occurs because my code of sharing arrays may be wrong. 
So I would like you to provide any example to use array in computation as mpc-as-a-service.

**Comment by KinanBab** [comment]
Okay, I will look into this and try to provide helpful examples or guidance

**Comment by ReoYoneyama** [comment]
Thank you very much! 
I'm looking forward to it!

**Comment by ReoYoneyama** [comment]
Hello. How's it going?
My goal is to provide a ML service that works on MPC(JIFF). So it's necessary to handle share of arrays.
However, it hasn't work properly these several weeks. I really appreciate if you could tell me any solution of that.

**Comment by palladionIT** [comment]
After 2 days of debugging I finally decided to check the issue tracker after I ran into the same issues. My code is fairly small and self contained and I can provide it if it helps you with debugging.

**Comment by wyatt-howe** [comment]
Hello and thanks for being patient with this bug.

We have been working carefully to be sure all the special cases in terms of arrays sharing, such as asymmetric senders and receivers, differently shaped arrays, unknown array lengths and their combinations will be fully supported.

As you have noticed, an updated version of the MPC as a service demo has been pushed to the `array_sharing` branch [here](https://github.com/multiparty/jiff/tree/array_sharing/demos/mpc-as-a-service), which makes uses of two newer methods, `share_nd_array` and `open_nd_array`.

The goal is to eventually have separate simpler functions called `share_array`, `share_matrix`, `receive_array`, etc. but hopefully looking off this array_sharing dev branch is enough to get your code working until we are able to complete our tests and then merge.

**Comment by ReoYoneyama** [comment]
It's really helpful for me! Thank you!

**Comment by p-flock** [comment]
these changes were merged into master: https://github.com/multiparty/jiff/commit/52217014dc9cafb7ce6fe354732c04fe9acf2178
