### ISSUE TITLE
Duplicate Party Id Allocation

### ISSUE THREAD

**Issue by palladionIT** [multiparty/jiff#199]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

I want to report a bug.

* **What is the current behavior?**

's1' one is assigned to the coordinator client **and** one compute party. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

This might be a documentation issue, or none at all if I am thinking too complicated. I setup 3 compute parties where one is derived from the coordinator. The compute party Ids are assigned automatically by the coordinator from the array in the config. So I specified in the config: compute_parties: ["s1", 2, 3] because 's1' is forced by the framework for the derived compute-coordinator. 

* **What is the expected behavior?**

Coordinator picks free id's. 

* **What is the motivation / use case for changing the behavior?**

My expectation was that in the config I have to specify all possible party ids in the computation. I think the easiest solution would be to document the forced id 's1' and that the compute_parties array is the array where the coordinator will choose from. Maybe also throwing an error when there are duplicate Ids in the computation would help. If this is already the case then the egde case with the compute-coordinator might be an oversight.

I hope my explanation is clear, if you need code examples I can cut unnecessary parts from my code and post it.

**Comment by p-flock** [comment]
Hi @palladionIT , thanks for submitting this issue. It would help me if you could post some of the code that the server is running or any errors that are output when you try and run your application. Are you experiencing an error when trying to run the computation? Or just that parties are being assigned IDs you do not expect?

I think you are right that the documentation around using the coordination-server as a compute party can be more clear.

**Comment by palladionIT** [comment]
I did some testing and it seems that the duplicate Ids causes some funky behavior. The wait_for(compute_parties) seems not to be triggered at the party with the same duplicate Id as the coordinator. Therefore, I can not really test the computations themselves. The coordinator (jiffServer instance) is producing "waiting for: s1,2,s1" if the config is as follows: ""compute_parties": ["s1", 2],". 
My code is a still messy Typescript variant of the server.js entry file from your tutorials. I outsourced the MPC part to another file that I cut from the code. It is used instead of the "//Setup MPC logic" comment. The issue even with this code is as stated above, wait_for is not triggered in the party with the same Id as the coordinator. It is triggered in the coordinator and the other compute party as far as I can see.

`import Storage from './Storage';
import MPC from './mpc-code/MPC';
import Coordinator from './Coordinator';

// Commandline parsing
console.log('Command line arguments: [party_id] [/path/to/configuration/file.json] [computation_id]');

// // Read config
let config: any = './config/config.json';
if (process.argv[3] != null) {
  config = process.argv[3];
}
config = require(config);

// // Read party ID
let party_id: number = 1; // this is currently not working or used
if (process.argv[2] != null || Number(process.argv[2]) != -1) {
  party_id = Number(process.argv[2]);
} else {
  party_id = config.party_id;
}

// // Read computation ID
let computation_id: string = 'default';
if (process.argv[4] != null) {
  computation_id = process.argv[4];
} else {
  computation_id = config.computation_id;
}

let jiffClient: any;

const clientOptions = {
  crypto_provider: config.preprocessing === false, // comment out if you want to use preprocessing
  party_count: config.party_count,
  initialization: { role: 'compute' }, // indicate to the server that this is a compute party
}

if (process.env.SERVER_TYPE && process.env.SERVER_TYPE === 'coordinator') {
  const jiffServer = new Coordinator(process.env.LISTEN_PORT, config.compute_parties, config.input_parties, config);
  const maxPartyCount = 6;
  jiffClient = jiffServer.getJiffClient(computation_id, maxPartyCount, clientOptions);
} else {
  // eslint-disable-next-line @typescript-eslint/no-var-requires, import/no-unresolved
  const JIFFClient: any = require('./lib/jiff-client.js');

  jiffClient = new JIFFClient('http://localhost:8080', computation_id, clientOptions);
}

jiffClient.wait_for(config.compute_parties, () : void => {
  // Setup MPC logic
});
`
I hope this helps.

**Comment by p-flock** [comment]
Hi. I was able to replicate this id allocation error by modifying the MPC-as-a-service demo to use the server as a compute party. I believe I have a solution which will help you resolve the issue on your end.

 If you are relying on a config file to specify party ids and party counts you can specify the 's1' id as a compute party, similar to this:
```
{
  "party_count": 4,
  "compute_parties": ['s1', 1, 2],
  "input_parties": [3, 4],
  "input_length": 3,
  "preprocessing": false
}
```
Notice that the party count is now 4, instead of 5, because the server is only connecting to 4 external parties. The party ids also range from 1-4 inclusive. 

the way I set up the server's compute instance is as follows:
```JavaScript
var jiffServer = new JIFFServer(http, options);
var computeOptions = {
  crypto_provider: config.preprocessing === false, preprocessing
  party_count: config.party_count,
  initialization: {role: 'compute'} 
}
jiffServer.computationMaps.maxCount['test'] = config.party_count;
var jiffClient = jiffServer.compute('test', computeOptions);
```

and an overridden hook handles assigning parties their ids and roles:
```Javascript
var options = {
  logs: true,
  hooks: {
    beforeInitialization: [
      function (jiff, computation_id, msg, params) {
        console.log('got called with', msg.role);
        if (params.party_id != null) {
          return params;
        }

        var search = config.compute_parties;
        var check = assignedCompute;
        if (msg.role === 'input') {
          search = config.input_parties;
          check = assignedInput;
        }

        for (var p = 0; p < search.length; p++) {
          var id = search[p];
          if (check[id] === true || id === 's1') {
            continue;
          }

          check[id] = true;
          params.party_id = id;
          return params;
        }

        return params;
      }
    ]
  }
};
```
Notice that there is a check to make sure none  of the external parties are given the 's1' id. Initially I did not include that check and experienced the same behavior that you saw, where a compute party was also assigned `id == 's1'`

I have included the same `compute()` function in both server.js and compute-party.js files, although it probably makes sense to have one file with is required and called in both the server and compute party.

The code I ran can be found here https://github.com/multiparty/jiff/tree/server_compute_party_tests/demos/mpc-as-a-service.

**Comment by palladionIT** [comment]
Thank you very much for your clarification! I did not fully understand the __beforeInitialization__ hook and just took it from the MPCaaS demo. Now it makes sense. 

Now that I checked the documentation again I think I found a small mistake in the JSDocs. 

> The hooks for this instance. Checkout the [hooks documentation](https://multiparty.org/jiff/docs/jsdoc/hooks.html).

The link to the hooks documentationt at [hooks@JSDoc](https://multiparty.org/jiff/docs/jsdoc/hooks.html) links to itself and not to the more expressive [documentation](https://github.com/multiparty/jiff/blob/server_compute_party_tests/lib/ext/Hooks.md) in the repository.


A similar issue with the extension url found [here](https://multiparty.org/jiff/docs/jsdoc/index.html) having a dead link instead of pointing to [this](https://github.com/multiparty/jiff/tree/server_compute_party_tests/lib/ext). I can make another issue if you think it is necessary. 

I close this one because your code resolves my initial issue — thank you.
