### ISSUE TITLE
Replace socket.io with standard Websocket library (RFC 6455 Websocket protocol)

### ISSUE THREAD

**Issue by p-flock** [multiparty/jiff#212]
The goal of this feature/replacement is to make JIFF compatible with standard, RFC compliant websockets. This has two desirable outcomes:

1.  RIFF clients will be able to connect to a JIFF Server (and vice versa) without needing to implement the socket.io protocol in Rust.
2. The native websockets should be faster than socket.io.

with one notable downside:

1. Older browsers (IE) may not support the new Websocket implementations (although many libraries try to address this)

There are 2 good candidate libraries as far as I can tell:

1. [ws](https://github.com/websockets/ws). ws is a node implementation, and to provide browser support we would have to use the [isomorphic-ws](https://github.com/heineiuo/isomorphic-ws) wrapper library, or potentially implement some custom logic to fall back on the native websocket implementation of the browser. My worry about ws-isomorphic is that it hasn't had much recent development (but maybe it doesn't need it though and it mostly keeps up-to-date with ws unless there are major changes to the base library)

2. [Websocket-Node](https://github.com/theturtle32/WebSocket-Node). This claims to support node and all modern browsers, would be great if it works. One concern is that it is less popular than ws so maybe the support and documentation is not as good ( ¯\_(ツ)_/¯ probably fine)

If we fall back on [native websockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API), we will definitely break compatibility with IE, and potentially Safari (not sure about Safari, some implementations seem to be missing according to the compatibility chart [here](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API), although apparently the latest versions are RFC compliant). 

First steps to investigate and pick an appropriate library or set of libraries:

1. Set up a prototype websocket server using ws (could be a [JIFF server refactored](https://github.com/multiparty/jiff/blob/master/lib/server/socket.js) to use ws instead of socket.io, but fine to just write a demo node server)
2. build a client script using ws, connect to the server via node
3. build a client script using ws-isomorphic, connect to the server via both node and browser
4. build a client script using websocket-node, connect to the server via both node and browser
5. build a client script using the native websocket API, and connect to the server from the browser

Then let's compare the ease and simplicity of each of the implementations, hopefully one of the two libraries works well in both Node and all the browsers. Also worth a shot to put in a condition to the demo-client that uses ws when in Node, and falls back on the native websocket API when in the browser (ex. of a similar switch we use in JIFF demos https://github.com/multiparty/jiff/blob/12afbc23fe6917bec59f9a70524fb0caf93a0def/demos/sum/mpc.js#L11)

**Comment by tsbraun1891** [comment]
Frederick mentioned possibly using WebRTC which is an alternate library that uses UDP.  We're not sure if it has been implemented in Rust though.

**Comment by stevenroussey-privicy** [comment]
What about peer-to-peer like WebRTC provides or libp2p. libp2p has implementations in most languages.

**Comment by KinanBab** [comment]
I think we have to be a bit careful here, I like the direction that the PR took using builtin websockets, I have used them for another project with a c++ backend and it went reasonably well.

I think the considerations I have about this are the following:
1. Any solution we propose needs to be compatible with rust for RIFF and with nodejs JIFF clients and nodejs server. The PR satisfies this.
2. Supporting Peer-to-peer communication without including the server in the mix is a long standing idea that we always talk about, this is a chance to make some progress in that regards, if our solution library has support for it, we do not need to implement this now, but it means that when we actually want to implement this, we wont have to change the sockets frameworks. I am unsure how the PR proposed solution affects this, WebRTC is ideally the best solution here.
3. We need to do some benchmarking here, even something as simple as running the base JIFF tests (but over actual network), just to see what performance impact we have when we switch the libraries. I honestly am not sure if sockets.io is fast/comparable to websockets or WebRTC, I presume it is slower?

**Comment by KinanBab** [comment]
I would not be too worried about WebRTC being implemented over UDP internally, WebRTC's protcol is configurable to ensure reliability and ordered delivery, which essentially will provide the same guarantees as TCP.

This definitely is going to make WebRTC slower than if it was configured to be non-reliable and non-order, but that is not important, what is important is comparing the speed of the reliable WebRTC vs sockets.io and websockets.

https://stackoverflow.com/questions/54292824/webrtc-channel-reliability

**Comment by TheoXD** [comment]
Thumbs up for libp2p suggestion, it's more future proof protocol in my opinion than Websocket or WebRTC directly. Please consider that option.
