### ISSUE TITLE
High level use-cases

### ISSUE THREAD

**Issue by 34r7h** [multiparty/jiff#227]
Hi there and thanks for this effort. I'm looking for a blackbox function engine that takes an encrypted function with encrypted data and returns encrypted data, without leaks throughout the process. If I'm in the right place, can you share an example of how a trivial function with some argument would be encrypted and computed between 3 parties?

**Comment by KinanBab** [comment]
I think you are in the right place. You can find a very simple example of what you are describing in our sum demo https://github.com/multiparty/jiff/tree/master/demos/sum. This is a simple example that secretly sums secret inputs from 3 or more parties and outputs the sum. You can find more complicated examples in the other demos in that directory.

I also recommend trying out the tutorials to gain more familiarity with JIFF's API. You can do this by cloning this repo, and then running `npm run tutorial` inside its root directory.

If you are looking for a more complicated example that has been deployed in real life, you can check out web-mpc (https://github.com/multiparty/web-mpc) which is a web application for securely collecting and aggregating secret data for analytics that uses JIFF as a back-end.

**Comment by 34r7h** [comment]
Thank you, kinan. i'll run the tuts and wrap my head around it more
