### ISSUE TITLE
Re-organize library files around roles.

### ISSUE THREAD

**Issue by lapets** [multiparty/jiff#25]
Rather than splitting the library into "server" and "client" components, we should organize them around roles:

* enabler/communications medium party (i.e., the "route messages" and "enable computations" role);
* compute party (this is where all the operator definitions should go);
* contributor party (maybe a limited version of the compute party that cannot actually do any computations);
* recipient party (again, very limited version of what is now a compute party).

Then, in a file that supports a a particular role in a particular scenario you would import some combination of the above as needed.

**Comment by KinanBab** [comment]
@lapets  do we still need this?

**Comment by lapets** [comment]
No, closing this for now. Given that anyone using JIFF will probably be integrating it into their own server-side and client-side web application components, the current separation seems most accessible and comprehensible.
