### ISSUE TITLE
Sorting/Shuffling Ideas

### ISSUE THREAD

**Issue by lucyq** [multiparty/jiff#28]

**Comment by KinanBab** [comment]
* Merge sort : many multiplications but less comparisons?
* Randomly choose whether to swap two elements or not. (O(n^2) random choices).

**Comment by lucyq** [comment]
We're going to be doing batcher's odd-even merge sort!

**Comment by KinanBab** [comment]
Batcher sort will definitely perform better than bubble sort, but we should compare it against Andrei's idea of shuffling without sorting (share n^2 random bits that dedicate which is a swap) and/or other shuffling without sorting ideas.

**Comment by lucyq** [comment]
Yes, agreed! We should do shuffling w/o sorting if it's more efficient but it would be interesting to compare diff. sorts
